### ISSUE TITLE
How do I get the demoH5File files of other cameras

### ISSUE THREAD

**Issue by yuyo15117** [SJTUzhou/3D-Teeth-Reconstruction-from-Five-Intra-oral-Images#5]
How do I get the following parameters?ex_rxyz, ex_txyz, focLth, dpix, u0, v0, rela_R, rela_t = readCameraParamsFromH5(
        h5File=demoH5File
    )

我感觉我的visualization.py获得的牙齿图像与原图像融合时并不对其，我怀疑时上面参数的问题

**Comment by SJTUzhou** [comment]
The function of "readCameraParamsFromH5" is defined in Line 72 in [visualization.py](https://github.com/SJTUzhou/3D-Teeth-Reconstruction-from-Five-Intra-oral-Images/blob/main/visualization.py).
我们目前的这个方法还是存在一定的问题，主要原因是三维模型投影得到的牙齿轮廓与图片中分割得到的牙齿轮廓在寻找对应点匹配关系时容易出现错误，导致重建效果较差，仍有很大的提升空间。

**Comment by yuyo15117** [comment]
非常感谢您的回复，我们在想，目前你们是通过五个角度的图片去对牙齿进行建模，但是效果还不是特别好，所有我们有一个疑问就是，是否可以将5个角度的图片变成更多角度的图片去对牙齿进行建模，以达到更好的建模效果？

**Comment by SJTUzhou** [comment]
我们的工作是对 Wu, C., Bradley, D., Garrido, P., Zollhöfer, M., Theobalt, C., Gross, M.H., & Beeler, T. (2016). Model-based teeth reconstruction. ACM Transactions on Graphics (TOG), 35, 1 - 13. 的工作的一个粗糙的复现，使它适用于我们的所需的正畸的场景。您可以阅读这篇论文，他们可以通过输入一段视频，实现三维牙齿重建。理论上输入一段视频，通过分析相邻帧之间的图像，可以使用structure from motion相关的算法直接找对应点关系，结合三维牙齿模型形变，实现更精准的三维重建。
