### ISSUE TITLE
How can I attach the original color and texture of teeth to this obj file？

### ISSUE THREAD

**Issue by yuyo15117** [SJTUzhou/3D-Teeth-Reconstruction-from-Five-Intra-oral-Images#6]

**Comment by yuyo15117** [comment]
How to paste the original color and texture of teeth back onto the generated OBJ file?

**Comment by SJTUzhou** [comment]
I think you can design your texture map and a mapping relationship with some extra files. This is common in obj but you need to pay attention to the position of triangle face and vertices.
