### ISSUE TITLE
How can I apply my own intraoral imaging data to this code? 

### ISSUE THREAD

**Issue by wang89280** [SJTUzhou/3D-Teeth-Reconstruction-from-Five-Intra-oral-Images#7]
How can I apply my own intraoral imaging data to this code? Also, why are there six intrinsic and extrinsic parameters here? How should I calculate the intrinsic and extrinsic parameters of my own intraoral imaging data to match the format of these intrinsic and extrinsic parameters? Please help me, thank you.

**Comment by SJTUzhou** [comment]
Those are the camera parameters. You can do camera calibration or finetune them by manual estimation to initialize the parameters.

**Comment by wang89280** [comment]
我所知道的旋转矩阵和平移矩阵都是3*3的矩阵，我现在获取口内照的3*3的rx、ry、rz矩阵，我如何转换为您论文中rx、ry、rz格式。

**Comment by SJTUzhou** [comment]
@wang89280 这个代码里用的应该是旋转向量表示旋转，和旋转矩阵有对应关系，具体的转换方式可以参考https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.html 旋转的表示方法有很多，欧拉角，四元数，旋转向量等等

**Comment by wang89280** [comment]
好的。非常感谢您的帮助。再打扰一下，还有个问题想请教一下，望您赐教。我想测试一下这个算法在我的自己的数据集上的效果，在已经获取相机内外参和口内照二值图像后，就可以使用了吗？还需要针对性的修改什么内容吗？

**Comment by SJTUzhou** [comment]
@wang89280 肯定需要具体调试，我当时在我自己的数据集上也调了很久，而且这个算法精度不高，主要还是牙齿轮廓不准确，你可以自己训练一个更精准的牙齿轮廓分割，加上牙位这个语义信息，使轮廓对应点关系更准确。
